// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cate1016/alfred-timetrack/api (interfaces: DriveService)

// Package automocks is a generated GoMock package.
package automocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDriveService is a mock of DriveService interface.
type MockDriveService struct {
	ctrl     *gomock.Controller
	recorder *MockDriveServiceMockRecorder
}

// MockDriveServiceMockRecorder is the mock recorder for MockDriveService.
type MockDriveServiceMockRecorder struct {
	mock *MockDriveService
}

// NewMockDriveService creates a new mock instance.
func NewMockDriveService(ctrl *gomock.Controller) *MockDriveService {
	mock := &MockDriveService{ctrl: ctrl}
	mock.recorder = &MockDriveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriveService) EXPECT() *MockDriveServiceMockRecorder {
	return m.recorder
}

// GetOrCreate mocks base method.
func (m *MockDriveService) GetOrCreate(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockDriveServiceMockRecorder) GetOrCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockDriveService)(nil).GetOrCreate), arg0)
}

// GetOrCreateSheet mocks base method.
func (m *MockDriveService) GetOrCreateSheet(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateSheet", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateSheet indicates an expected call of GetOrCreateSheet.
func (mr *MockDriveServiceMockRecorder) GetOrCreateSheet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateSheet", reflect.TypeOf((*MockDriveService)(nil).GetOrCreateSheet), arg0, arg1)
}
