// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cate1016/alfred-timetrack/api (interfaces: SheetService)

// Package automocks is a generated GoMock package.
package automocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSheetService is a mock of SheetService interface.
type MockSheetService struct {
	ctrl     *gomock.Controller
	recorder *MockSheetServiceMockRecorder
}

// MockSheetServiceMockRecorder is the mock recorder for MockSheetService.
type MockSheetServiceMockRecorder struct {
	mock *MockSheetService
}

// NewMockSheetService creates a new mock instance.
func NewMockSheetService(ctrl *gomock.Controller) *MockSheetService {
	mock := &MockSheetService{ctrl: ctrl}
	mock.recorder = &MockSheetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetService) EXPECT() *MockSheetServiceMockRecorder {
	return m.recorder
}

// AppendField mocks base method.
func (m *MockSheetService) AppendField(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendField", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendField indicates an expected call of AppendField.
func (mr *MockSheetServiceMockRecorder) AppendField(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendField", reflect.TypeOf((*MockSheetService)(nil).AppendField), arg0, arg1, arg2)
}

// TimetrackSheetInitialize mocks base method.
func (m *MockSheetService) TimetrackSheetInitialize(arg0 string, arg1, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimetrackSheetInitialize", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TimetrackSheetInitialize indicates an expected call of TimetrackSheetInitialize.
func (mr *MockSheetServiceMockRecorder) TimetrackSheetInitialize(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimetrackSheetInitialize", reflect.TypeOf((*MockSheetService)(nil).TimetrackSheetInitialize), arg0, arg1, arg2)
}
